name: mne
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python=3.6.8
- pip
- mkl
- cython
- flake8
- h5py
- joblib
- jupyter
- keras
- matplotlib
- numexpr
- numpy
- numpydoc
- pandas
- pillow
- psutil
- pylint
- pyqt>=5.9
- pytest
- pytest-cov
- pytest-mock
- pytest-timeout
- scikit-learn
- scipy
- spyder
- sqlalchemy
- sqlite
- statsmodels
- tensorflow
- xlrd
- traits>=4.6.0
- pyface>=6
- traitsui>=6
- testpath<0.4
- pip:
  - mne
  - vtk
  - https://api.github.com/repos/enthought/mayavi/zipball/226189a6ad3dc3c01d031ef21d0d0cde554ac851
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - pytest-faulthandler
  - pytest-sugar
  - pydocstyle
  - codespell
  - python-picard
